### ISSUE TITLE
Better Separate Data File and Markdown file

### ISSUE THREAD

**Issue by kkweon** [hunkim/deep_architecture_genealogy#8]
It's better to have a separate data file (preferrably, yaml format) 
and let the python script autogenerates the markdown file.

I guess there is a data file(`Neural Net Arch Genealogy.txt`), 
**but it's not included in the repository because of the gitignore.**

```python
with open('Neural Net Arch Genealogy.txt') as fin, open('README.md', 'w') as fout:
    fout.write(head)
    for line in fin:
        tab_count = line.count('\t')
        if not tab_count:
            continue

        spaces = ['  ' for i in range(tab_count-1)]
        fout.write(''.join(spaces) + '* ' + line.replace('\t', ''))

    fout.write(tail)
```

## Suggesstion
1. Include a data file
2. Change the data file to yaml format or json format such that it is easy to generate a markdown format

For example,

- each paper has `name`, `date`, `link`
- categories can have `data`
- categories can have another sub categories

It would look like this

```yaml
---
Memory Networks:
  data:
  - name: Memory Network
    date: '14.10'
    link: https://arxiv.org/abs/1410.3916

  - name: End to End Memory Network
    date: '15.03'
    link: https://arxiv.org/pdf/1503.08895.pdf

  Neural Programming:
    data:
    - name: Neural Turing Machine
      date: '14.10'
      link: https://arxiv.org/pdf/1410.5401.pdf

    - name: Neural Random-Access Machine
      date: '16.02'
      link: https://arxiv.org/pdf/1511.06392.pdf

CNN:
  data:
  - name: Some CNNs
    date: Some Cnn Date
    link: Some CNN Link

```
